[build]
  base    = "client"
  command = "npm install && npm run build"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' https: data:; img-src 'self' data: https:; connect-src 'self' https:;"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
